apiVersion: v1
kind: Namespace
metadata:
  name: agentregistry
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: agentregistry
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/den-vasyliev/charts/agentregistry
  ref:
    tag: "0.5.16"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agentregistry-inventory
  namespace: agentregistry
spec:
  interval: 1h
  releaseName: agentregistry-inventory
  chartRef:
    kind: OCIRepository
    name: agentregistry
    namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      tag: "0.5.18"
    disableAuth: true
