apiVersion: v1
kind: Namespace
metadata:
  name: mcp
---
apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: echo-mcp-server
  namespace: mcp
  labels:
    kagent.dev/discovery: "disabled"
spec:
  deployment:
    cmd: npx
    args:
      - "@muhtalipdede/echo-mcp-server"
    port: 3000
  stdioTransport: {}
  transportType: stdio